org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

# help running gradle file
org.gradle.daemon=true                 # Keep Gradle daemon running
org.gradle.parallel=true               # Build modules in parallel
org.gradle.configureondemand=true      # Configure only requested modules
org.gradle.caching=true                # Enable build cachingyye